services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: php-login-logout-php
    working_dir: /php-login-logout/public_docroot
    volumes:
      - ./:/php-login-logout
      - ./public_docroot:/php-login-logout/public_docroot
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php/php-fpm.conf
      - ./docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - tmp:/var/run
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: php-login-logout-nginx
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./public_docroot:/php-login-logout/public_docroot
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - tmp:/var/run
    depends_on:
      - php
volumes:
  tmp:
